// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'input': string;
  'stu-login-form': string;
  'submit-btn': string;
}
export const cssExports: CssExports;
export default cssExports;
