// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'stu-system-logo': string;
  'thumb': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
