// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon': string;
  'stu-login-succeed': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
