// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'main-title': string;
  'stu-login-module': string;
}
export const cssExports: CssExports;
export default cssExports;
